### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by albertsun** [buth/kubernetes-dns-reverse-proxy#2]
Right now the test suite only has a benchmark script. We should at least have something basic to run before we push new tags. At least lets not break the default fall through behavior.

How should go tests be written anyway? Do we need unit and integration tests?

**Comment by ericandrewlewis** [comment]
Had a good session with JP today talking about testing Go code. I created a [testing branch](https://github.com/newsdev/kubernetes-dns-reverse-proxy/tree/testing) and started [moving the reverse proxy out of the main program](https://github.com/newsdev/kubernetes-dns-reverse-proxy/commit/3a955d517b6a1d84ddb5c6d09e49933dc6f44ee6) to make it testable. 

This breaks the program at the moment because I don't really know how to write Go. Will link up with @buth to chat about next steps.

**Comment by albertsun** [comment]
Sounds like a good plan. Can you merge this `redirects` branch where we had implemented the 301s https://github.com/newsdev/kubernetes-dns-reverse-proxy/tree/redirects before it diverges too far from master?

**Comment by buth** [comment]
Awesome! Yes, in this and a few other portions of the infrastructure code too much is in-lined in main. (This is mostly out of haste/laziness on my part.)

**Comment by ericandrewlewis** [comment]
> Can you merge this `redirects` branch

I'd like to hold off on that. The reorganization is still in flux. Once it makes more sense to me I'm glad to rebase.

**Comment by ericandrewlewis** [comment]
#9 has been merged. :confetti_ball: I'm going to close this as complete for now. Let's open new issues if more tests should be added.
