### ISSUE TITLE
Implement 301 redirects feature

### ISSUE THREAD

**Issue by albertsun** [buth/kubernetes-dns-reverse-proxy#4]
If a leading `/` denotes static, no leading slash denotes an app name, perhaps a `>` should mean redirect to this URL.

Like this perhaps?

```
{
  "test.newsdev.net": {
    "/": ">test.new.newsdev.net"
  }
}
```

**Comment by bkoski** [comment]
@albertsun @samjacoby and I just took a look at this.  It seems like one thing that's different about redirects is that they're "synthetic" responses, i.e. the response should be returned directly by the server rather than proxying to some remote service that provides the 301.

From what we could reckon it seems like this would involve changing the "main" server:

```
    reverseProxyServer := &http.Server{
        Addr:    config.address,
        Handler: reverseProxy,
    }
```

to have a custom `Handler`.  This `Handler` would resolve the route.  If it's a redirect, it would be immediately returned.  Otherwise, the request would be routed to the reverse proxy handler.

Here's some terrible, hopelessly broken psuedogo illustrating this:

``` go
mainServer = &http.Server{
    Addr:    config.address,
    Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      root, err := d.Service(req.Host, req.URL.Path)
      if(root == null) {
        fallthorugh.hanlde()
      }
      else if(route.redirect) {
        http.response.code = 301

      } else if(route) {
        reverseProxy.handle(route)


      }
    }),
  }

    go func() {
    log.Println("starting server on", config.address)
    errs <- mainServer.ListenAndServe()
  }()

```

Tomorrow we'll continue to see if this is even workable...

**Comment by albertsun** [comment]
Working in https://github.com/newsdev/kubernetes-dns-reverse-proxy/commit/1ecfe2006daf82530f21b48e69fbf18c07eba2ad
